version: '3.10'


services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - sqlite_data:/app/db.sqlite3  # Mount the SQLite database file to a Docker volume
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  sqlite_data:  # Define a named volume for SQLite persistence
